---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 859c9850cb36cdc8e9684ac6c63f112c6900e9fc
    app.quarkus.io/build-timestamp: 2023-05-10 - 14:37:03 +0000
  labels:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: neuron
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 859c9850cb36cdc8e9684ac6c63f112c6900e9fc
    app.quarkus.io/build-timestamp: 2023-05-10 - 14:37:03 +0000
  labels:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: neuron
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neuron
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 859c9850cb36cdc8e9684ac6c63f112c6900e9fc
        app.quarkus.io/build-timestamp: 2023-05-10 - 14:37:03 +0000
      labels:
        app.kubernetes.io/name: neuron
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - command:
            - java
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: uther/neuron:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: neuron
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
