---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: c5a09eb754bc6fa67e7c3f5c86df39be9d2f95b7
    app.quarkus.io/build-timestamp: 2022-09-08 - 09:53:20 +0000
  labels:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: neuron
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: neuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: c5a09eb754bc6fa67e7c3f5c86df39be9d2f95b7
    app.quarkus.io/build-timestamp: 2022-09-08 - 09:53:20 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: neuron
  name: neuron
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: neuron
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: c5a09eb754bc6fa67e7c3f5c86df39be9d2f95b7
        app.quarkus.io/build-timestamp: 2022-09-08 - 09:53:20 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: neuron
    spec:
      containers:
        - command:
            - java
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: uther/neuron:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: neuron
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
