---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: triggertest3
spec:
  broker: default
  filter:
    attributes:
      type: testevent3
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: kneuron00003
