apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    boson.dev/function: 'true'
    boson.dev/runtime: quarkus
    function.knative.dev: 'true'
    function.knative.dev/runtime: quarkus
  name: neuron01
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: WATCHMAN
              value: >-
                http://watchman.endpoint
            - name: NEURONID
              value: "000002"
          image: image-registry.openshift-image-registry.svc:5000/kneurondemo/neuron:1.0.0-SNAPSHOT            
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 0
          name: user-container
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 0
            successThreshold: 1
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 60
  traffic:
    - latestRevision: true
      percent: 100
