apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kneural
  labels:
    app.kubernetes.io/component: kneural
    app.kubernetes.io/instance: kneural
    app.kubernetes.io/name: kneural
    app.kubernetes.io/part-of: kneural-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '100'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
      labels:
        app.kubernetes.io/component: kneural
        app.kubernetes.io/instance: kneural
        app.kubernetes.io/part-of: kneural-app
        app.openshift.io/runtime: java
        app.openshift.io/runtime-version: openjdk-17-ubi8
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: TARGETFILE
              value: /test/output.txt
            - name: NEURONID
              value: '000001'
          image: >-
            image-registry.openshift-image-registry.svc:5000/serverlessdemo/neuron:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: kneural
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
          volumeMounts:
            - mountPath: /test
              name: test-f133a459
      enableServiceLinks: false
      timeoutSeconds: 300
      volumes:
        - name: test-f133a459
          persistentVolumeClaim:
            claimName: persisttest
  traffic:
    - latestRevision: true
      percent: 100
