---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-persisttest
spec:
  broker: default
  filter:
    attributes:
      type: persistRequest
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: kneural

