---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: triggertest1
spec:
  broker: default
  filter:
    attributes:
      type: testevent1
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: kneuron00001
