---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: d3891a98037ad8b52790e86263c1b2c7ec99226a
    app.quarkus.io/build-timestamp: 2023-10-16 - 09:34:52 +0000
  labels:
    app.kubernetes.io/name: kneuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: kneuron
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: kneuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: d3891a98037ad8b52790e86263c1b2c7ec99226a
    app.quarkus.io/build-timestamp: 2023-10-16 - 09:34:52 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: kneuron
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kneuron
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kneuron
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: d3891a98037ad8b52790e86263c1b2c7ec99226a
        app.quarkus.io/build-timestamp: 2023-10-16 - 09:34:52 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: kneuron
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: uther/kneuron:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: kneuron
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
