apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: neuralcache
spec:
  clusterName: infinispan
  name: neuralYAMLcache
  template: |
  distributedCache:
    mode: "SYNC"
    owners: "2"
    statistics: "true"
    encoding:
      mediaType: "application/x-protostream"
    persistence:
      fileStore: ~
